### PR TITLE
feat!: use latest generator rc release in the action

### PR DESCRIPTION
**Pull request by derberg**
**Description**

- use latest generator rc release in the action

Action tested here https://github.com/derberg/test-experiment (pointing to the fork of course) and as you can see it works https://github.com/derberg/test-experiment/runs/1395229220?check_suite_focus=true

### CODE REVIEW

**Comment by arvid-villen-adtoox** [comment]
any updates on this?

**Comment by derberg** [comment]
@arvid-villen-adtoox hey, the idea is to merge it once the generator is released with 1.0.0 which is soon, max 2 weeks (🤞 )

Is it blocking you?

**Comment by arvid-villen-adtoox** [comment]
Hi,
thanks for the update!

If it is released in the near future (which it sounds like) then we won’t be blocked by this :)

**Comment by derberg** [comment]
@arvid-villen-adtoox as you can see it is released under 1.0.0 and starting from this release we will also provide v1 so all new features and patches that do not break compatibility will be not only released with semantic releases but also always bumped under v1

**Comment by arvid-villen-adtoox** [comment]
@derberg Thanks!
I somehow did not receive a notification. I have now tested it and it works great :)

The only note I have is that your PR changed `WaleedAshraf/asyncapi-github-action@v0.0.3` to `WaleedAshraf/asyncapi-github-action@v1` in `README.md` but the correct value is `WaleedAshraf/asyncapi-github-action@v0.0.4`.

Anyway, thanks a lot for the fix!

**Comment by derberg** [comment]
@arvid-villen-adtoox Awesome it works as expected 💪 
Would you mind opening a PR for the issue in the readme?

**Pull request merged**
