### PR TITLE
fix: move from node 16 to 14 because of failing docker build

### PR DESCRIPTION
**Pull request by victormartingarcia**
**Description**
Fixes the dev dependencies build error https://github.com/asyncapi/github-action-for-generator/issues/232#issuecomment-1218155509

**Related issue(s)**
See also https://github.com/asyncapi/github-action-for-generator/issues/232

### CODE REVIEW

**Comment by victormartingarcia** [comment]
@derberg downgrading the image to node 14 works on my local docker env, but mysteriously it is falling on the pipeline: https://github.com/asyncapi/github-action-for-generator/runs/7893944814?check_suite_focus=true

Any ideas how to fix it?

**Comment by derberg** [comment]
@victormartingarcia ah damn, yeah, sorry, the thing is that if we do not install `devDependencies` then we won't be able to prepare the package as `ncc` is missing.

there are 2 options:
- let us just downgrade to node 14, but still install all dependencies
- move `@npmcli/run-script` and `@vercel/ncc` from `devDependencies` to `dependencies`

I'm ok with any, as in the end it is just a GH Action

**Comment by victormartingarcia** [comment]
@derberg looks like everything is green now :)

I went for the first option. Installing dev dependencies on the docker build

**Review by derberg — APPROVED** [review]

**Comment by victormartingarcia** [comment]
@derberg thanks for the support ! 🔝

**Comment by derberg** [comment]
@victormartingarcia thanks a lot for taking time to contribute 🙏🏼

**Comment by derberg** [comment]
@all-contributors please add @victormartingarcia for code

**Pull request merged**
